version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29
    environment:
      _JAVA_OPTIONS: "-Xmx1500m -XX:ParallelGCThreads=2 -XX:ConcGCThreads=2 -XX:ParallelGCThreads=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2"
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "myExpenses/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "myExpenses/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew lintAcraConscriptRelease testAcraConscriptRelease assembleAcraConscriptForTestAndroidTest --no-daemon
      - store_artifacts:
          path: myExpenses/build/reports
          destination: reports
      - store_test_results:
          path: myExpenses/build/test-results


